apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong-event-gateway
  namespace: keg
  labels:
    app: kong-event-gateway
    app.kubernetes.io/part-of: kafka
    app.kubernetes.io/name: kong-event-gateway
    app.kubernetes.io/component: integration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong-event-gateway
  template:
    metadata:
      labels:
        app: kong-event-gateway
      annotations:
        k8s.grafana.com/scrape: "true"
        k8s.grafana.com/metrics.path: "/health/metrics"
        k8s.grafana.com/metrics.portNumber: "8080"
    spec:
      containers:
        - name: gateway
          image: kong/kong-native-event-proxy-dev@sha256:6671ff86cd07cb8e603d5e296771f4b7ece8cb1672ce2b74f25815cb268ef0d4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9092
            - containerPort: 9094
            - containerPort: 8080
          volumeMounts:
            - name: internal-tls-secret
              mountPath: /var/tls/internal
              readOnly: true
            - name: external-tls-secret
              mountPath: /var/tls/external
              readOnly: true
          envFrom:
            - secretRef:
                name: konnect-env-secret
          env:
            - name: KNEP__OBSERVABILITY__LOG_FLAGS
              value: "info,knep=info"
          readinessProbe:
            httpGet:
              path: /health/probes/readiness
              port: 8080
          livenessProbe:
            httpGet:
              path: /health/probes/liveness
              port: 8080
          resources:
            requests:
              memory: 0.5Gi
              cpu: 500m
            limits:
              memory: 1Gi
              cpu: 750m
      terminationGracePeriodSeconds: 30
      volumes:
        - name: internal-tls-secret
          secret:
            secretName: keg-internal-tls-secret
        - name: external-tls-secret
          secret:
            secretName: keg-external-tls-secret
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kong-event-gateway
  name: kong-event-gateway
  namespace: keg
spec:
  ports:
    - name: internal
      port: 9092
      protocol: TCP
      targetPort: 9092
    - name: external
      port: 9094
      protocol: TCP
      targetPort: 9094
    - name: health
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: kong-event-gateway
  type: ClusterIP
---

